name: Challenge readme maker
on: ['push']

jobs:
  readme-generator:
    runs-on: ubuntu-20.04
    steps:
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' 

      - uses: actions/checkout@v3
        id: github-checkout

      - id: file_changes
        uses: trilom/file-changes-action@v1.2.3
        with:
          output: ','
          fileOutput: ','

      - name: readme maker
        run: |
          echo "${{ steps.file_changes.outputs.files }}"