name: Challenge readme maker
on: ['push']

jobs:
  readme-generator:
    runs-on: ubuntu-20.04
    env:
      GET_FILES: scripts/readme_gen.sh
      GEN_MD: scripts/make_readme.py
      PY_REQ_PATH: scripts/requirements.txt

    steps:
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
          
      - name: Installing PY packages
        run: |
          echo $(ls)
      
      - uses: actions/checkout@v3
        id: github-checkout

      - id: file_changes
        uses: trilom/file-changes-action@v1.2.3
        with:
          output: ','
          fileOutput: ','

      - name: readme maker
        run: |
          "$GET_FILES" "${{ steps.file_changes.outputs.files }}"

      - name: Push changes
        run: |
          git config user.name GitHub Action
          git config user.email github-actions@github.com
          git status
          git add .
          git commit -m "Added challenge README"
          git push 
        