name: Main readme maker
on: ['push']

jobs:
  readme-generator:
    runs-on: ubuntu-20.04
    env:
      GEN_MD: scripts/make_main_readme.py
      PY_REQ_PATH: scripts/requirements.txt

    steps:
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11' 
      
      - uses: actions/checkout@v3
        id: github-checkout

      - name: Installing PY packages
        run: |
          pip install -r "$PY_REQ_PATH"

      - name: readme maker
        run: |
          python3 "$GEN_MD"

      - name: Push changes
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git pull
            git config user.name GitHub Action
            git config user.email github-actions@github.com
            git status
            git add .
            git commit -m "Added challenge README"
            git push 
          else
            echo "Nothing to commit"
          fi
        